# Generated by Django 5.2.17 on 2026-08-07 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_otpchallenge_branchmembership'),
        ('salons', '0003_salon_is_featured_salon_rating_average_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='salons.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سالن مورد علاقه',
                'verbose_name_plural': 'سالن\u200cهای مورد علاقه',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'salon'), name='unique_favorite_salon')],
            },
        ),
    ]
