# Generated by Django 5.2.17 on 2026-08-07 11:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favoritesalon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='customers/avatars/', validators=[core.validators.validate_image_size], verbose_name='تصویر'),
        ),
    ]
