# Generated by Django 5.2.17 on 2026-08-09 17:32

from django.db import migrations, models


def merge_operational_roles_into_admin(apps, schema_editor):
    user_model = apps.get_model("accounts", "User")
    user_model.objects.filter(role__in=("support", "finance")).update(role="admin")


def restore_operational_roles(apps, schema_editor):
    # The former role cannot be inferred after the merge, so rollback keeps
    # these accounts as administrators instead of guessing permissions.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customerprofile_avatar'),
    ]

    operations = [
        migrations.RunPython(merge_operational_roles_into_admin, restore_operational_roles),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('salon_owner', 'مالک سالن'), ('branch_manager', 'مدیر شعبه'), ('receptionist', 'پذیرش'), ('staff', 'آرایشگر'), ('admin', 'مدیر کل')], db_index=True, default='customer', max_length=24, verbose_name='نقش'),
        ),
    ]
