# Generated by Django 5.2.17 on 2026-08-07 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0003_salon_is_featured_salon_rating_average_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('confirmed', 'تأییدشده'), ('completed', 'انجام\u200cشده'), ('cancelled', 'لغوشده'), ('no_show', 'عدم حضور')], db_index=True, default='pending_payment', max_length=20)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('total_price', models.PositiveBigIntegerField()),
                ('deposit_amount', models.PositiveBigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='salons.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='salons.staff')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ('-start_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('branch_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='salons.branchservice')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='salons.staff')),
            ],
            options={
                'verbose_name': 'آیتم رزرو',
                'verbose_name_plural': 'آیتم\u200cهای رزرو',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['staff', 'start_at', 'end_at'], name='bookings_bo_staff_i_dd0a12_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['branch', 'status', 'start_at'], name='bookings_bo_branch__f3646d_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__lte', models.F('total_price'))), name='booking_deposit_lte_total'),
        ),
    ]
