# Generated by Django 5.2.17 on 2026-08-14 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_historical_walk_ins(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    AuditLog = apps.get_model("core", "AuditLog")
    ids = []
    for target_id in AuditLog.objects.filter(
        action="booking.manual_created", target_type="bookings.Booking"
    ).values_list("target_id", flat=True):
        try:
            ids.append(int(target_id))
        except (TypeError, ValueError):
            continue
    Booking.objects.filter(pk__in=ids).update(source="walk_in")


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_discount_amount_discountcode_and_more'),
        ('core', '0002_supportticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('online', 'آنلاین'), ('walk_in', 'حضوری')], db_index=True, default='online', max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('awaiting_verification', 'در انتظار تأیید واریز'), ('confirmed', 'تأییدشده'), ('completed', 'انجام\u200cشده'), ('cancelled', 'لغوشده'), ('no_show', 'عدم حضور')], db_index=True, default='pending_payment', max_length=24),
        ),
        migrations.RunPython(mark_historical_walk_ins, migrations.RunPython.noop),
    ]
