# Generated by Django 5.2.17 on 2026-08-07 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_discount_amount_discountcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('booking_confirmed', 'تأیید رزرو'), ('booking_reminder', 'یادآوری رزرو'), ('booking_cancelled', 'لغو رزرو')], max_length=24)),
                ('channel', models.CharField(choices=[('sms', 'پیامک'), ('in_app', 'داخل برنامه')], default='sms', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='bookings.booking')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('recipient', 'booking', 'event', 'channel'), name='unique_booking_event_notification')],
            },
        ),
    ]
