# Generated by Django 5.2.17 on 2026-08-07 11:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='reviews/%Y/%m/', validators=[core.validators.validate_image_size]),
        ),
    ]
