# Generated by Django 5.2.17 on 2026-08-07 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviewimage_image'),
        ('salons', '0004_alter_salonimage_image_alter_staff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='salons.staff'),
        ),
        migrations.AddField(
            model_name='review',
            name='value_rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
