# Generated by Django 5.2.17 on 2026-08-07 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('type', models.CharField(choices=[('deposit', 'بیعانه'), ('full', 'پرداخت کامل'), ('remainder', 'مانده')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق'), ('refunded', 'بازپرداخت\u200cشده')], db_index=True, default='pending', max_length=12)),
                ('method', models.CharField(choices=[('online', 'آنلاین'), ('cash', 'نقدی'), ('wallet', 'کیف پول')], default='online', max_length=12)),
                ('gateway_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('provider', models.CharField(default='mock', max_length=40)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('requested', 'درخواست\u200cشده'), ('paid', 'واریزشده'), ('rejected', 'ردشده')], db_index=True, default='requested', max_length=12)),
                ('bank_account', models.CharField(max_length=40)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'تسویه',
                'verbose_name_plural': 'تسویه\u200cها',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='مبلغ مثبت برای بستانکار و منفی برای بدهکار')),
                ('type', models.CharField(choices=[('refund', 'بازپرداخت'), ('salon_earning', 'درآمد سالن'), ('commission', 'کارمزد سامانه'), ('settlement', 'تسویه'), ('adjustment', 'اصلاح دستی')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='bookings.booking')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('related_booking__isnull', False)), fields=('wallet', 'related_booking', 'type'), name='unique_wallet_booking_transaction_type')],
            },
        ),
    ]
