# Generated by Django 5.2.17 on 2026-08-14 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_historical_salons(apps, schema_editor):
    WalletTransaction = apps.get_model("payments", "WalletTransaction")
    Settlement = apps.get_model("payments", "Settlement")
    Salon = apps.get_model("salons", "Salon")
    for transaction in WalletTransaction.objects.filter(
        related_booking__isnull=False, salon__isnull=True
    ).select_related("related_booking__branch"):
        transaction.salon_id = transaction.related_booking.branch.salon_id
        transaction.save(update_fields=("salon",))
    for settlement in Settlement.objects.filter(salon__isnull=True).select_related("wallet"):
        salon_ids = list(
            Salon.objects.filter(owner_id=settlement.wallet.user_id).values_list("id", flat=True)[:2]
        )
        if len(salon_ids) == 1:
            settlement.salon_id = salon_ids[0]
            settlement.save(update_fields=("salon",))


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('salons', '0005_branchclosure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, upload_to='payments/receipts/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlement',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='salons.salon'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('card_to_card', 'کارت\u200cبه\u200cکارت'), ('online', 'آنلاین'), ('cash', 'نقدی'), ('wallet', 'کیف پول')], default='in_person', max_length=16),
        ),
        migrations.RunPython(assign_historical_salons, migrations.RunPython.noop),
    ]
