# Generated by Django 5.2.17 on 2026-08-07 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام شهر')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='شناسه URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام منطقه')),
                ('slug', models.SlugField(max_length=120, verbose_name='شناسه URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='salons.city')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'مناطق',
                'ordering': ('city__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='نام سالن')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='شناسه URL')),
                ('type', models.CharField(choices=[('women', 'زنانه'), ('men', 'مردانه'), ('unisex', 'مشترک')], max_length=12, verbose_name='نوع سالن')),
                ('description', models.TextField(blank=True, verbose_name='معرفی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('suspended', 'تعلیق\u200cشده')], db_index=True, default='draft', max_length=12, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='علت رد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سالن',
                'verbose_name_plural': 'سالن\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='شعبه مرکزی', max_length=120, verbose_name='نام شعبه')),
                ('address', models.TextField(verbose_name='نشانی')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(max_length=16, verbose_name='تلفن')),
                ('working_hours', models.JSONField(blank=True, default=dict, verbose_name='ساعات کاری')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='امکانات')),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='گام تقویم')),
                ('preparation_buffer_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='زمان آماده\u200cسازی')),
                ('deposit_percent', models.PositiveSmallIntegerField(default=20, verbose_name='درصد بیعانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='salons.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='salons.district')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='salons.salon')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبه\u200cها',
                'ordering': ('salon__name', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='unique_district_slug_per_city'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('salon', 'name'), name='unique_branch_name_per_salon'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_percent__lte', 100)), name='branch_deposit_percent_lte_100'),
        ),
    ]
