# Generated by Django 5.2.17 on 2026-08-07 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salons/gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='salons.salon')),
            ],
            options={
                'verbose_name': 'تصویر سالن',
                'verbose_name_plural': 'تصاویر سالن',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(blank=True, help_text='خالی بودن سالن یعنی خدمت مرکزی سامانه است.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ('category__sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BranchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (تومان)')),
                ('price_type', models.CharField(choices=[('fixed', 'ثابت'), ('starting_from', 'شروع از')], default='fixed', max_length=16, verbose_name='نوع قیمت')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='مدت (دقیقه)')),
                ('preparation_buffer_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='زمان آماده\u200cسازی اختصاصی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_services', to='salons.branch')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_services', to='salons.service')),
            ],
            options={
                'verbose_name': 'خدمت شعبه',
                'verbose_name_plural': 'خدمات شعبه',
                'ordering': ('service__category__sort_order', 'service__name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='شناسه URL')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='نام آیکن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='salons.servicecategory')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خدمت',
                'verbose_name_plural': 'دسته\u200cبندی خدمات',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='salons.servicecategory'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('photo', models.ImageField(blank=True, upload_to='staff/photos/', verbose_name='تصویر')),
                ('bio', models.TextField(blank=True, verbose_name='معرفی')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='سال تجربه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='salons.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آرایشگر',
                'verbose_name_plural': 'پرسنل',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_override', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت اختصاصی')),
                ('duration_override_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدت اختصاصی')),
                ('branch_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='salons.branchservice')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='salons.staff')),
            ],
            options={
                'verbose_name': 'مهارت آرایشگر',
                'verbose_name_plural': 'مهارت\u200cهای آرایشگر',
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='پایان')),
                ('is_off', models.BooleanField(default=False, verbose_name='تعطیل')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='salons.staff')),
            ],
            options={
                'verbose_name': 'شیفت آرایشگر',
                'verbose_name_plural': 'شیفت\u200cهای آرایشگر',
                'ordering': ('day_of_week', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='StaffTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='شروع مرخصی')),
                ('ends_at', models.DateTimeField(verbose_name='پایان مرخصی')),
                ('reason', models.CharField(blank=True, max_length=250, verbose_name='علت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='salons.staff')),
            ],
            options={
                'verbose_name': 'مرخصی آرایشگر',
                'verbose_name_plural': 'مرخصی\u200cهای آرایشگر',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='branchservice',
            constraint=models.UniqueConstraint(fields=('branch', 'service'), name='unique_service_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='branchservice',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='branch_service_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('salon', 'category', 'name'), name='unique_service_per_salon_category'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.UniqueConstraint(fields=('staff', 'branch_service'), name='unique_service_per_staff'),
        ),
        migrations.AddConstraint(
            model_name='staffshift',
            constraint=models.UniqueConstraint(fields=('staff', 'day_of_week'), name='unique_staff_day_shift'),
        ),
    ]
