# Generated by Django 5.2.17 on 2026-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salonimage_service_branchservice_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='پیشنهاد ویژه'),
        ),
        migrations.AddField(
            model_name='salon',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='میانگین امتیاز'),
        ),
        migrations.AddField(
            model_name='salon',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد نظر'),
        ),
    ]
