# Generated by Django 5.2.17 on 2026-08-07 11:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_salon_is_featured_salon_rating_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonimage',
            name='image',
            field=models.ImageField(upload_to='salons/gallery/%Y/%m/', validators=[core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, upload_to='staff/photos/', validators=[core.validators.validate_image_size], verbose_name='تصویر'),
        ),
    ]
