# Generated by Django 5.2.17 on 2026-08-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_salonimage_image_alter_staff_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='شروع تعطیلی')),
                ('ends_at', models.DateTimeField(verbose_name='پایان تعطیلی')),
                ('reason', models.CharField(blank=True, max_length=250, verbose_name='علت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='salons.branch')),
            ],
            options={
                'verbose_name': 'تعطیلی شعبه',
                'verbose_name_plural': 'تعطیلی\u200cهای شعبه',
                'ordering': ('-starts_at',),
                'indexes': [models.Index(fields=['branch', 'starts_at', 'ends_at'], name='salons_bran_branch__533b3f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='branch_closure_ends_after_start')],
            },
        ),
    ]
